#!/usr/bin/env bash

set -xe

source /common.sh
install_cleanup_trap

unpack /filesystem /
chown -R pi:pi /home/pi

function download_and_extract {
    sudo -u pi mkdir -p "$1"
    cd "$1"
    wget -O tmp.zip "$(curl -s "https://api.github.com/repos/$2/releases/latest" | grep -o "http.*${3:-\.zip}")"
    unzip tmp.zip
    rm tmp.zip
    chown -R pi:pi "$1"
}

download_and_extract "/home/pi/marlinraker" "pauhull/marlinraker"
sudo -u pi npm install

download_and_extract "/home/pi/marlinraker_files/www" "mainsail-crew/mainsail"

systemctl_if_exists enable marlinraker.service